configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/harvard-business-school-mpatankar%2Ftrain-travel-friction-analysis-144c021dcc1e7bd78801831c34d0442465f765858a7833b45636434e50142c88.yml
