configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/harvard-business-school-mpatankar%2Ftrain-travel-friction-analysis-4deb38dc7dcb12f3f162fcdc2d49163ed57ec8f081eb460e4756776b93e63ab9.yml
