configured_endpoints: 7
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/harvard-business-school-mpatankar%2Ftrain-travel-friction-analysis-790078f00640bfc5c681a97cc93d4664e40c654303f66570255279cd92960481.yml
